trigger:
  branches:
    include:
      - main

pr:
  branches:
    include:
      - main

pool:
  name: Default

variables:
  buildConfiguration: 'Release'

stages:
  - stage: BuildAndTest
    displayName: 'CI Pipeline'
    jobs:
      - job: Build
        steps:
          - task: UseDotNet@2
            inputs:
              version: '8.x'
              packageType: sdk

          - script: dotnet restore
            displayName: 'Restore'

          - script: dotnet test ./tests/CounterApi.Tests.csproj --no-build
            displayName: 'Run Tests'

          - script: dotnet build ./src/CounterApi.csproj -c $(buildConfiguration)
            displayName: 'Build App'

          - script: dotnet publish ./src/CounterApi.csproj -c $(buildConfiguration) -o $(Build.ArtifactStagingDirectory)
            displayName: 'Publish App'

          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: '$(Build.ArtifactStagingDirectory)/src.zip'
              ArtifactName: 'drop'
